import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

interface FieldDefinition {
  readonly name: string;
  readonly type: string;
  readonly description: string;
}

interface SchemaDefinition {
  readonly structName: string;
  readonly description: string;
  readonly fields: readonly FieldDefinition[];
  readonly reliabilityEnum: readonly string[];
}

export const defaultLocalizationSchema: SchemaDefinition = {
  structName: 'LocalizationUniform',
  description:
    'Represents localization-derived metrics that feed rotor fusion and shader uniforms. Values are normalized to [0,1] unless noted otherwise.',
  fields: [
    { name: 'stageConfidence', type: 'f32', description: 'Confidence in stage/world transform fidelity.' },
    { name: 'anchorConfidence', type: 'f32', description: 'Confidence in active spatial anchor stability.' },
    { name: 'drift', type: 'f32', description: 'Normalized drift between frames.' },
    { name: 'latencySeconds', type: 'f32', description: 'Latest localization latency in seconds.' },
    { name: 'translation', type: 'vec3<f32>', description: 'World-space translation extracted from localization dual quaternion.' },
  ],
  reliabilityEnum: ['High', 'Medium', 'Low'],
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const OUTPUT_DIR = path.join(ROOT, 'generated', 'localization');

const header = '// Auto-generated by tools/codegen/localization-quaternions.ts\n// DO NOT EDIT DIRECTLY.\n\n';

const ARTIFACT_FILENAMES = {
  typescript: 'localization-uniform.ts',
  wgsl: 'localization-uniform.wgsl',
  csharp: 'LocalizationUniform.cs',
  readme: 'README.md'
} as const;

function buildTypeScript(schemaDef: SchemaDefinition): string {
  const interfaceFields = schemaDef.fields
    .map(field => `  /** ${field.description} */\n  ${field.name}: ${field.type === 'vec3<f32>' ? '[number, number, number]' : 'number'};`)
    .join('\n\n');

  const reliabilityUnion = schemaDef.reliabilityEnum.map(value => `'${value.toLowerCase()}'`).join(' | ');

  return `${header}export type LocalizationReliabilityLevel = ${reliabilityUnion};\n\nexport interface ${schemaDef.structName}Descriptor {\n${interfaceFields}\n}\n\nexport const LOCALIZATION_UNIFORM_FIELDS = ${JSON.stringify(schemaDef.fields, null, 2)} as const;\n`;
}

function buildWGSL(schemaDef: SchemaDefinition): string {
  const wgslFields = schemaDef.fields
    .map(field => `  ${field.name}: ${field.type}; // ${field.description}`)
    .join('\n');
  return `${header}struct ${schemaDef.structName} {\n${wgslFields}\n};\n`;
}

function buildCSharp(schemaDef: SchemaDefinition): string {
  const csharpFields = schemaDef.fields
    .map(field => {
      const type = field.type === 'vec3<f32>' ? 'Vector3' : 'float';
      return `    /// <summary>${field.description}</summary>\n    public ${type} ${capitalize(field.name)};`;
    })
    .join('\n\n');

  return `${header}using System.Runtime.InteropServices;\nusing UnityEngine;\n\n[StructLayout(LayoutKind.Sequential)]\npublic struct ${schemaDef.structName}CSharp {\n${csharpFields}\n}\n`;
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

export interface LocalizationArtifacts {
  readonly typescript: string;
  readonly wgsl: string;
  readonly csharp: string;
  readonly readme: string;
}

export function generateLocalizationArtifacts(schemaDef: SchemaDefinition = defaultLocalizationSchema): LocalizationArtifacts {
  const typescript = buildTypeScript(schemaDef);
  const wgsl = buildWGSL(schemaDef);
  const csharp = buildCSharp(schemaDef);
  const readme = `${header}Generated localization uniform schema.\n\n- TypeScript: \`generated/localization/${ARTIFACT_FILENAMES.typescript}\`\n- WGSL: \`generated/localization/${ARTIFACT_FILENAMES.wgsl}\`\n- C#: \`generated/localization/${ARTIFACT_FILENAMES.csharp}\`\n`;

  return { typescript, wgsl, csharp, readme };
}

export async function writeLocalizationArtifacts(
  outputDir: string = OUTPUT_DIR,
  schemaDef: SchemaDefinition = defaultLocalizationSchema
): Promise<void> {
  const artifacts = generateLocalizationArtifacts(schemaDef);
  await fs.mkdir(outputDir, { recursive: true });

  const files: Array<[string, string]> = [
    [ARTIFACT_FILENAMES.typescript, artifacts.typescript],
    [ARTIFACT_FILENAMES.wgsl, artifacts.wgsl],
    [ARTIFACT_FILENAMES.csharp, artifacts.csharp],
    [ARTIFACT_FILENAMES.readme, artifacts.readme]
  ];

  await Promise.all(files.map(([filename, content]) => fs.writeFile(path.join(outputDir, filename), content, 'utf8')));
}

async function run(): Promise<void> {
  await writeLocalizationArtifacts();
  // eslint-disable-next-line no-console
  console.log(`Localization schema artifacts written to ${OUTPUT_DIR}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  run().catch(error => {
    // eslint-disable-next-line no-console
    console.error('Localization code generation failed:', error);
    process.exitCode = 1;
  });
}
