import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

interface FieldDefinition {
  readonly name: string;
  readonly type: string;
  readonly description: string;
}

interface SchemaDefinition {
  readonly structName: string;
  readonly description: string;
  readonly fields: readonly FieldDefinition[];
  readonly reliabilityEnum: readonly string[];
}

const schema: SchemaDefinition = {
  structName: 'LocalizationUniform',
  description:
    'Represents localization-derived metrics that feed rotor fusion and shader uniforms. Values are normalized to [0,1] unless noted otherwise.',
  fields: [
    { name: 'stageConfidence', type: 'f32', description: 'Confidence in stage/world transform fidelity.' },
    { name: 'anchorConfidence', type: 'f32', description: 'Confidence in active spatial anchor stability.' },
    { name: 'drift', type: 'f32', description: 'Normalized drift between frames.' },
    { name: 'latencySeconds', type: 'f32', description: 'Latest localization latency in seconds.' },
    { name: 'translation', type: 'vec3<f32>', description: 'World-space translation extracted from localization dual quaternion.' },
  ],
  reliabilityEnum: ['High', 'Medium', 'Low'],
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const OUTPUT_DIR = path.join(ROOT, 'generated', 'localization');

const header = '// Auto-generated by tools/codegen/localization-quaternions.ts\n// DO NOT EDIT DIRECTLY.\n\n';

function buildTypeScript(schemaDef: SchemaDefinition): string {
  const interfaceFields = schemaDef.fields
    .map(field => `  /** ${field.description} */\n  ${field.name}: ${field.type === 'vec3<f32>' ? '[number, number, number]' : 'number'};`)
    .join('\n\n');

  const reliabilityUnion = schemaDef.reliabilityEnum.map(value => `'${value.toLowerCase()}'`).join(' | ');

  return `${header}export type LocalizationReliabilityLevel = ${reliabilityUnion};\n\nexport interface ${schemaDef.structName}Descriptor {\n${interfaceFields}\n}\n\nexport const LOCALIZATION_UNIFORM_FIELDS = ${JSON.stringify(schemaDef.fields, null, 2)} as const;\n`;
}

function buildWGSL(schemaDef: SchemaDefinition): string {
  const wgslFields = schemaDef.fields
    .map(field => `  ${field.name}: ${field.type}; // ${field.description}`)
    .join('\n');
  return `${header}struct ${schemaDef.structName} {\n${wgslFields}\n};\n`;
}

function buildCSharp(schemaDef: SchemaDefinition): string {
  const csharpFields = schemaDef.fields
    .map(field => {
      const type = field.type === 'vec3<f32>' ? 'Vector3' : 'float';
      return `    /// <summary>${field.description}</summary>\n    public ${type} ${capitalize(field.name)};`;
    })
    .join('\n\n');

  return `${header}using System.Runtime.InteropServices;\nusing UnityEngine;\n\n[StructLayout(LayoutKind.Sequential)]\npublic struct ${schemaDef.structName}CSharp {\n${csharpFields}\n}\n`;
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

async function run(): Promise<void> {
  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  const tsPath = path.join(OUTPUT_DIR, 'localization-uniform.ts');
  const wgslPath = path.join(OUTPUT_DIR, 'localization-uniform.wgsl');
  const csPath = path.join(OUTPUT_DIR, 'LocalizationUniform.cs');

  await Promise.all([
    fs.writeFile(tsPath, buildTypeScript(schema), 'utf8'),
    fs.writeFile(wgslPath, buildWGSL(schema), 'utf8'),
    fs.writeFile(csPath, buildCSharp(schema), 'utf8'),
  ]);

  await fs.writeFile(
    path.join(OUTPUT_DIR, 'README.md'),
    `${header}Generated localization uniform schema.\n\n- TypeScript: \`${path.relative(ROOT, tsPath)}\`\n- WGSL: \`${path.relative(ROOT, wgslPath)}\`\n- C#: \`${path.relative(ROOT, csPath)}\`\n`,
    'utf8'
  );

  // eslint-disable-next-line no-console
  console.log(`Localization schema artifacts written to ${OUTPUT_DIR}`);
}

run().catch(error => {
  // eslint-disable-next-line no-console
  console.error('Localization code generation failed:', error);
  process.exitCode = 1;
});
